version: '3.7'

services:

  testwebsite:
    container_name: testwebsite
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  default:
    name: nginxproxymanager_default
    extern: true
